### ISSUE TITLE
Tip for new users

### ISSUE THREAD

**Issue by cesarsouza** [vivet/HungarianAlgorithm#17]
Hi @vivet !

I've just recently seen that you project has been one of the default go-to's for people who are migrating from the Accord.NET framework, which has been discontinued few months ago. I am opening this issue to ask if you would be willing to indicate in your readme that your implementation could be used as a replacement for the [Munkres/Hungarian algorithm](http://accord-framework.net/docs/html/T_Accord_Math_Optimization_Munkres.htm) that was once available in Accord. This way, people who were once using the Accord implementation would know that a separate implementation also exists in your repository and that it is being currently maintained. 

Cheers!
Cesar

**Comment by vivet** [comment]
Hi
I think it should be the other ways around. 
On top of that finding this library shouldn't be hard - maybe I am wrong, but then I would rather improve that.

**Comment by cesarsouza** [comment]
Yes, actually you are right. The thing is that I have already archived that project so I can't update it anymore (not even the readme).

But in any case, just wanted to thank you for sharing your work. I still receive messages from people asking what they should use now that Accord.NET has been achieved and have been directing them here. Hopefully also the existence of this issue may also help other users come towards here.

Cheers!
Cesar
