### ISSUE TITLE
After integration of the class unity crashes at play

### ISSUE THREAD

**Issue by Draghont** [vivet/HungarianAlgorithm#18]
Hello, I have integrated the class in my code, but after pressing play in unity it crashes.

What is weird is that if I press play with int[] result = HungarianAlgorithm.FindAssignments(costs); commented and remove comment during play the result array is returned correctly.

Any suggestions?
Thanks for your effort in realizing this class!

**Comment by Draghont** [comment]
Hi,
it was just a matter of squaring the size of the array, I didn't notice the during init the array was passed to the algorithm with different dimensions, this caused the crash.
Squaring it fixed the issue.

BTW I had also to make the namespace and class name different to have it work on Unity. 

Thank you again for your effort in making this available to everybody.
D

**Comment by vivet** [comment]
No problem, and good luck with your project
