### ISSUE TITLE
Clarify copyright/licensing

### ISSUE THREAD

**Issue by kevinoid** [vivet/HungarianAlgorithm#2]
Thanks for publishing and maintaining this NuGet package!  I am reviewing implementations of the Hungarian Algorithm for a project that I am working on and was hoping you could clarify the copyright/licensing of this package.

It looks like the implementation is based on Alex Regueiro's implementation from http://blog.noldorin.com/2009/09/hungarian-algorithm-in-csharp/.  His copyright statement was removed and the license changed from MIT to the Unlicense in 6fdbdf9.  Did you receive a copyright assignment, or permission to relicense the code?

Thanks,
Kevin

**Comment by vivet** [comment]
Hi
The link is dead.

**Comment by kevinoid** [comment]
I'm not sure what that has to do with the copyright, but you can access it on the Internet Archive if you would like:

https://web.archive.org/web/20121113123739if_/http://blog.noldorin.com/2009/09/hungarian-algorithm-in-csharp/

**Comment by vivet** [comment]
Hi
The original source doesn't really exists anymore.
Also I don't think there are any actual copyrights registered, as the algorithm isn't owned by anyone (from 1955). So wether the license should be MIT, you can still use the library as you like.

**Comment by kevinoid** [comment]
I'm afraid copyright does not expire when the original host of a work disappears.  You are correct that the algorithm is not patented, but copyright covers implementations of an algorithm rather than the algorithm itself.  So unless the author has disclaimed their copyright, or the copyright has expired (from the date the implementation was written), it would still apply.

If you don't find that argument persuasive, how about giving credit where credit is due?  I don't think it would diminish the work you have done, since packaging and maintaining is certainly not easy.  But if @alexreg wrote the original code, it seems only fair to give him credit for writing it by acknowledging that where appropriate.

**Comment by vivet** [comment]
Hi
I agree. 
I merely wanted a NuGet package some time ago, why I made the project. And I then cleaned the code for comments (don't like that in code).

I will look into it, and talk to Alex. See what he wants.

**Comment by kevinoid** [comment]
Great, thanks @vivet!

**Comment by alexreg** [comment]
Hi @vivet. Indeed, this looks like it was based on code I wrote a number of years ago, albeit perhaps passing through several forms, so don't worry much about the attribution being lost. That said, I think @kevinoid for pointing this out and the rules around it. Altogether I'm fairly easy-going with licensing: the original MIT licence still applies, but I am happy to additionally (dual) license that code as BSD. Those are my two preferred licences, which I feel offer good compatibility with others. Does that sound okay going forwards?

**Comment by vivet** [comment]
What if i just change it to MIT License. I am thinking that might be easiest. 
Also do you want to add some credit for you in the readme.md for example?

**Comment by vivet** [comment]
Also was it you that I invited on LinkedIn, or someone else ?

**Comment by vivet** [comment]
I have changed the license to MIT

**Comment by kevinoid** [comment]
Looks good to me.  I'm looking forward to using it!

Thanks @vivet!  I really appreciate your willingness to work on the licensing details and for being accommodating.

Also thanks @alexreg for weighing in and being very reasonable with your licensing and attribution requests.
