### ISSUE TITLE
Calculations using decimal costs

### ISSUE THREAD

**Issue by tejaspatel182** [vivet/HungarianAlgorithm#20]
Just realised that the calculation are based on integer values only. I've made the changes on my local copy to use decimal types which works for both int and decimal.

This might an enhancement to switch between data types perhaps?

**Comment by vivet** [comment]
Hi
I only fix bugs for the project, sorry.
Also its quite easy to convert decimal scores to integers.

**Comment by tejaspatel182** [comment]
Agreed, I'll close this issue now, thanks for your work on this 👍
