### ISSUE TITLE
SquareArray Performance Problem

### ISSUE THREAD

**Issue by cihangiremir** [vivet/HungarianAlgorithm#21]
Hi,
 
When you use the SquareArray method, you may experience performance problems if your array size is too large.
The reason for this is that when you try to make the array square, it gets too many index range errors.

In this case the array size is greater than 750.
![image](https://github.com/vivet/HungarianAlgorithm/assets/47067655/08ddebd5-a5ac-45cd-bfa1-44b5a3f2e775)

When you change the original code as follows, the performance problem will disappear.
```csharp

    public static T[,] SquareArray<T>(this T[][] array)
    {
        if (array == null)
            throw new ArgumentNullException(nameof(array));

        var rows = array.Length;
        var cols = array.Select(x => x.Length).Concat(new[] { 0 }).Max();
        var loops = rows > cols ? rows : cols;
        var square = new T[loops, loops];

        for (var i = 0; i < loops; i++)
        {
            // break loop if i bigger than row
            if (i > rows - 1)
                break;
            for (var j = 0; j < loops; j++)
            {
                // break loop if j bigger than cols
                if (j > cols - 1)
                    break;
                square[i, j] = array[i][j];
            }
        }

        return square;
    }
```

Same array size but new code

![image](https://github.com/vivet/HungarianAlgorithm/assets/47067655/fd8a0703-a3dd-4a74-ae06-8bbe06b336e8)

**Comment by vivet** [comment]
Hi
I will take a look at updating the implementation.

**Comment by vivet** [comment]
It's fixed. I updated the implementation with yours
