### ISSUE TITLE
返回的值是什么意思呢？ What does the returned value mean?

### ISSUE THREAD

**Issue by ping9719** [vivet/HungarianAlgorithm#22]
img1
![image](https://github.com/vivet/HungarianAlgorithm/assets/9651046/7343ddc5-4221-497c-949b-60c6799a9af1)

```
var matrix1 = new int[,]
{
    {1,1,0},
    {1,1,0},
    {0,0,1},
};

var v = HungarianAlgorithm.HungarianAlgorithm.FindAssignments(matrix1);
```
img2
![image](https://github.com/vivet/HungarianAlgorithm/assets/9651046/99b3ca1a-ae4f-4361-941f-54497bc4b84f)

数组[2,0,1]的含义是什么呢？
What is the meaning of the array [2,0,1]?

我想得到{x1,Y2},{x2,Y1},{x3,Y3},应该怎么办？
I want {x1,Y2},{x2,Y1},{x3,Y3}. What should I do?

或者{x1,Y1},{x2,Y2},{x3,Y3}.
or{x1,Y1},{x2,Y2},{x3,Y3}.

**Comment by vivet** [comment]
Try read the Readme. It returns index of matches. Otherwise I suggest reading a bit more about the algorithm.
