### ISSUE TITLE
When not eligible

### ISSUE THREAD

**Issue by baytekink** [vivet/HungarianAlgorithm#5]
Hello,
What data must we give when it is not eligible one x to one y ?

Thx

**Comment by vivet** [comment]
You can use the SqaureArray() method, to insert nulls

**Comment by baytekink** [comment]
Of cource I may use, but in the SquareArray it assign null to int[i,j] which takes compile error. You can not assign null to int value. So is there another option?

**Comment by vivet** [comment]
Nullable int, or square the array yourself

**Comment by baytekink** [comment]
I see, but Hungarian algorithm works with int[,], so I do not have chance to make it nullable. Thank you for your advice anyway.
